# .github/workflows/ci.yml

# Name of the workflow
name: Node.js CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ "main" ]
  # Triggers the workflow on pull request events for the main branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # A strategy for multi-version testing (optional, but good practice)
    strategy:
      matrix:
        node-version: [20.x] # Using a recent Long-Term Support (LTS) version

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up the specified version of Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Caches npm dependencies for faster builds

      # Installs project dependencies
      - name: Install dependencies
        run: npm install

      # Runs the build script to compile TypeScript
      - name: Build project
        run: npm run build

      # Runs the test script
      - name: Run tests
        run: npm test